# Generated by Django 4.2.25 on 2025-10-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories_app.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategorySimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_a', to='categories_app.category')),
                ('category_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_b', to='categories_app.category')),
            ],
            options={
                'indexes': [models.Index(fields=['category_a', 'category_b'], name='categories__categor_16c0a0_idx'), models.Index(fields=['category_b', 'category_a'], name='categories__categor_8d78bb_idx')],
                'unique_together': {('category_a', 'category_b')},
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'name'], name='categories__parent__891485_idx'),
        ),
    ]
